# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Use a slim Python image
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy application code
COPY mcp_server.py /app/

# Install dependencies
RUN pip install --no-cache-dir httpx mcp-server

# Expose no port since this is stdio

# Default command (overridden by MCP platform)
CMD ["python", "mcp_server.py"]
